// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okzsimhiwidiuzkwjsqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9renNpbWhpd2lkaXV6a3dqc3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTY2MjcsImV4cCI6MjA3Mjk3MjYyN30.SZ7I_Oih7jzYXwpfBAd6QYdKxaey1BGJOop4ownDvu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});